def calling_things():
	works_fine()
	throws_an_exception()
	
calling_things()